### ISSUE TITLE
@gp-b2g, why you are closing all issues without resolving them?

### ISSUE THREAD

**Issue by laukstein** [gp-b2g/gp-peak-kernel#32]

**Comment by gp-b2g** [comment]
We send you a private mail with the reason.

Most of issues are not kernel related.

The channels to manage issues are our forum and bugzilla (remember to add gp@geeksphone.com on the bug)

Regards.

**Comment by laukstein** [comment]
Done as you suggested.

**Comment by gp-b2g** [comment]
Thanks!
