### ISSUE TITLE
Geeksphone peak swapfile

### ISSUE THREAD

**Issue by extraymond** [gp-b2g/gp-peak-kernel#34]
Hi! Is that possible to use swap file on peak?
I can use adb shell to create and mount a swapfile, but the phone is not using it.
I'm thinking maybe there are extra steps I need to do to enable swap.

**Comment by gp-b2g** [comment]
Swap is supported on Peak, this is not the place for this messages, please only use github to colaborate on a specific project bug.
For Swapping do a search on google to know what you need.
For these requests, use our forum please.
