### ISSUE TITLE
#875711 Add editor for /etc/hosts

### ISSUE THREAD

**Issue by laukstein** [gp-b2g/gp-peak-kernel#9]
Issue https://bugzilla.mozilla.org/show_bug.cgi?id=875711

**Comment by mcepl** [comment]
Firefox OS is meant for the end-consumer phones. Either write your own app to do it (you will need probably at least a privileged app), or ask somebody else to do it, but this shouldn't be part of the normal system, IMHO.

I would vote for WONTFIX here.

**Comment by laukstein** [comment]
It requires certified API access and is not available to third-party apps (most app developers will not have access to it), because it's reserved for Mozilla. And certified app must be approved for a device by the OEM or carrier.
